//import Head from "next/head";
import "./globals.css";
import Provider from "../components/provider";
import Navbar from "../components/Navbar";
import Loader from "../components/Loader";
import Link from "next/link";

export const metadata = {
  title: "Portefolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr-FR">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body>
        <Provider>
          <Loader />
          <div className="circle"></div>
          <div className="min-h-screen grid grid-rows-[auto,1fr,auto]">
            <Navbar />

            {children}
            <footer className="border-t-4 border-double border-custom-brown">
              <div className="flex justify-center gap-2.5 p-3  text-base ">
                <p>@copyright2024 |</p>
                <Link href="/">Mentions Légales</Link>
                <Link href="/">RGPD</Link>
              </div>
            </footer>
          </div>
        </Provider>
      </body>
    </html>
  );
}
